### ISSUE TITLE
[Request]: Suppression de l'opérateur from dans les mergeMap

### ISSUE THREAD

**Issue by lou-theo** [sfeir-open-source/sfeir-school-rxjs#19]
### Simplification souhaitée

Les exercices et leur correction utilise l'opérateur `from` pour convertir les arrays (de slice ou boxOfPie selon les cas) en une liste d'Observables au sein des mergeMap.
L'opérateur est toutefois inutile car l'opération est faite automatiquement par l'opérateur `mergeMap` comme a pu le découvrir @kuroidoruido lors de la captation disponible de la school RxJs.

L'opérateur `from` a d'ailleurs déjà été supprimé de la correction de la step 2.

### Détails des explications
Extrait de la doc RxJs
> Maps each value to an Observable, then flattens all of these inner Observables using [mergeAll](https://rxjs.dev/api/index/function/mergeAll).

mergeAll prend en entrée un `ObservableInput` (qu'il va donc flatten) dont la définition est
```ts
type ObservableInput<T> = Observable<T> | InteropObservable<T> | AsyncIterable<T> | PromiseLike<T> | ArrayLike<T> | Iterable<T> | ReadableStreamLike<T>;
```

Nous pouvons ainsi voir que `ArrayLike` est un type valide d'entrée et qu'il va donc être flatten avant d'être converti en une liste d'Observable

### Describe the solution you'd like

Supprimer l'utilisation de l'opérateur `from` partout mais mettre un commentaire dans la correction de la step 2 expliquant que cela revient au même avec ou sans le from

**Comment by kuroidoruido** [comment]
Pour moi c'est complètement ok de faire ça. En effet je n'ai pas eu le temps de revenir sur la school pour faire cette correction
