### ISSUE TITLE
[Request]: Simplification des callbacks dans les exercices

### ISSUE THREAD

**Issue by lou-theo** [sfeir-open-source/sfeir-school-rxjs#20]
### Is your feature request related to a problem? Please describe.

Très tôt dans la présentation de la school, nous avons cette slide

> ## Rappels : passer une fonction en paramètre
> ```typescript
> const numbers = [1,2,3,4,5,6];
> function isEven(n: number): boolean {
>     return n % 2 === 0;
> }
> const evenNumbers = numbers.filter((n) => isEven(n));
> // ou
> const evenNumbers = numbers.filter(isEven);
> ```

Au travers des différents exercices il y a de nombreux cas où cette simplification est applicable, notamment avec l'ensemble des `console.log|error`. C'est d'ailleurs ce qui est fait pour les `tap` dans la correction de la step 5.

### Describe the solution you'd like

Simplifier les exercices et leur correction afin de passer directement des fonctions en paramètre des opérateurs RxJS & subscribles (lorsque pertinent) afin de réduire la masse de code et augmenter la visibilité.

On peut raisonnablement se demander si cette syntaxe ne perdrait pas les apprenants qui y sont peu familier.
Toutefois la règle parait assez simple et rien n'oblige les apprenants de s'en servir.

### Describe alternatives you've considered

Ne rien faire

**Comment by kuroidoruido** [comment]
Pour moi c'est ok, pour les console.log|error j'ai tendance à passer par une arrow function par habitude mais en effet ce serait mieux de ne pas le faire au moins pour tous les cas où ça ne gène pas du tout la lecture
