### ISSUE TITLE
[Bug]: Mise en conformité School

### ISSUE THREAD

**Issue by jefBinomed** [sfeir-open-source/sfeir-school-rxjs#26]
### Describe the bug

Faire les petites taches suivantes pour clean la School 

- [x] Passage du thème en 3.2.0-rc
- [x] Check qu'il n'y a que main en branche 
- [x] Supprimer les classes inutilisées en lien avec les précédentes versions du thème

### Expected behavior

...

**Comment by kuroidoruido** [comment]
"3.2.0-rc" ? Release Candidate ? Pourquoi migrer avant que la release soit finie ?

**Comment by jefBinomed** [comment]
car je veux la tester sur une school :p et qu'en soit la rc est quasi finale (je pense avoir rien oublié dessus)
